#+TITLE:     How to Create and Manage Vocabularies
#+AUTHOR:    Dashamir Hoxha
#+EMAIL:     dashohoxha@gmail.com
# #+DESCRIPTION:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:nil LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
# #+INFOJS_OPT: view:overview toc:t ltoc:t mouse:#aadddd buttons:0 path:org-info.js
#+STYLE: <link rel="stylesheet" type="text/css" href="org-info.css" />

* Installing the FirefoxOS application

  #+begin_html
  <style type="text/css">
  .btn {
    background: #34d960;
    background-image: -webkit-linear-gradient(top, #34d960, #42b82b);
    background-image: -moz-linear-gradient(top, #34d960, #42b82b);
    background-image: -ms-linear-gradient(top, #34d960, #42b82b);
    background-image: -o-linear-gradient(top, #34d960, #42b82b);
    background-image: linear-gradient(to bottom, #34d960, #42b82b);
    -webkit-border-radius: 10;
    -moz-border-radius: 10;
    border-radius: 10px;
    -webkit-box-shadow: 2px 2px 3px #666666;
    -moz-box-shadow: 2px 2px 3px #666666;
    box-shadow: 2px 2px 3px #666666;
    font-family: Arial;
    color: #ffffff;
    font-size: 20px;
    padding: 10px 20px 10px 20px;
    text-decoration: none;
  }
  .btn:hover {
    background: #34b81a;
    background-image: -webkit-linear-gradient(top, #34b81a, #149127);
    background-image: -moz-linear-gradient(top, #34b81a, #149127);
    background-image: -ms-linear-gradient(top, #34b81a, #149127);
    background-image: -o-linear-gradient(top, #34b81a, #149127);
    background-image: linear-gradient(to bottom, #34b81a, #149127);
    text-decoration: none;
  }
  </style>

  <script type="text/javascript">
  function installVocabularyOnFFOS() {
      var manifestUrl = 'http://v.btranslator.org/manifest.webapp';
      var request = window.navigator.mozApps.install(manifestUrl);
      request.onsuccess = function () {
	  // Save the App object that is returned
	  var appRecord = this.result;
	  alert('Installation successful!');
      };
      request.onerror = function () {
	  // Display the error information from the DOMError object
	  alert('Install failed, error: ' + this.error.name);
      };
  }
  </script>

  <div style="padding: 10px;">
    <a href="javascript:installVocabularyOnFFOS();" class="btn">Install on Firefox OS</a>
    <a href="https://marketplace.firefox.com/app/vocabulary/" class="btn">View on the Marketplace</a>
  </div>
  #+end_html

* Installing the mobile application

  - Fork https://github.com/B-Translator/vocabulary-jquery or
    https://github.com/FreeSoft-AL/vocabulary on GitHub.

  - Make *gh-pages* the default branch on GitHub. GitHub will
    automatically publish this branch to an address like this:
    http://freesoft-al.github.io/vocabulary (it may take a few minutes
    for it to be published).

  - Optionally create a custom domain (as described [[https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/][here]]) and redirect
    it to GitHub.

  - Customize the application by editing the file [[https://github.com/FreeSoft-AL/vocabulary/blob/gh-pages/config.js][config.js]]. Some of
    the things that need to be changed are app_url, disqus.shortname,
    etc. The oauth2 settings can be left untouched.

  - Customize the list of available languages and vocabularies by
    editing [[https://github.com/FreeSoft-AL/vocabulary/blob/gh-pages/js/options.js][js/options.js]]. These vocabularies must have been created
    on the server first.
  

* Embedding inside a webpage

  It can also be embedded in a frame inside an HTML page, like the
  example shown here.
 
  #+begin_html
  <!-- HTML generated using hilite.me -->
  <div><pre style="margin-bottom: 10px; line-height: 125%"><span style="color: #6ab825; font-weight: bold">&lt;div</span> <span style="color: #bbbbbb">style=</span><span style="color: #ed9d13">&quot;width:300px; display:inline-block; float:right;</span>
  <span style="color: #ed9d13">            border:1px solid #aaa; padding:0px; margin-left:10px;&quot;</span><span style="color: #6ab825; font-weight: bold">&gt;</span>
    <span style="color: #6ab825; font-weight: bold">&lt;iframe</span> <span style="color: #bbbbbb">src=</span><span style="color: #ed9d13">&quot;http://v.btranslator.org?lng=sq&amp;proj=ICT_sq&quot;</span>
	    <span style="color: #bbbbbb">width=</span><span style="color: #ed9d13">&quot;100%&quot;</span> <span style="color: #bbbbbb">height=</span><span style="color: #ed9d13">&quot;395px&quot;</span>
	    <span style="color: #bbbbbb">seamless=</span><span style="color: #ed9d13">&quot;seamless&quot;</span> <span style="color: #bbbbbb">frameborder=</span><span style="color: #ed9d13">&quot;0&quot;</span><span style="color: #6ab825; font-weight: bold">&gt;</span>
    <span style="color: #6ab825; font-weight: bold">&lt;/iframe&gt;</span>
  <span style="color: #6ab825; font-weight: bold">&lt;/div&gt;</span>
  </pre></div>
  <!-- End HTML generated using hilite.me -->
  #+end_html

  #+begin_html
  <!-- HTML generated using hilite.me -->
  <div><pre style="margin-bottom: 10px; line-height: 125%"><span style="color: #6ab825; font-weight: bold">&lt;div</span> <span style="color: #bbbbbb">style=</span><span style="color: #ed9d13">&quot;width:300px; display:inline-block;</span>
  <span style="color: #ed9d13">	    float:right; border:1px solid #aaa; padding:5px;&quot;</span><span style="color: #6ab825; font-weight: bold">&gt;</span>
    <span style="color: #6ab825; font-weight: bold">&lt;h3</span> <span style="color: #bbbbbb">style=</span><span style="color: #ed9d13">&quot;margin-top:0px; color:#2a2;&quot;</span><span style="color: #6ab825; font-weight: bold">&gt;</span>Vocabulary: ICT_sq<span style="color: #6ab825; font-weight: bold">&lt;/h3&gt;</span>

    <span style="color: #6ab825; font-weight: bold">&lt;iframe</span> <span style="color: #bbbbbb">src=</span><span style="color: #ed9d13">&quot;https://btranslator.org/vocabulary/ICT_sq?display=iframe&quot;</span>
	    <span style="color: #bbbbbb">width=</span><span style="color: #ed9d13">&quot;100%&quot;</span> <span style="color: #bbbbbb">height=</span><span style="color: #ed9d13">&quot;350px&quot;</span>
	    <span style="color: #bbbbbb">seamless=</span><span style="color: #ed9d13">&quot;seamless&quot;</span> <span style="color: #bbbbbb">frameborder=</span><span style="color: #ed9d13">&quot;0&quot;</span><span style="color: #6ab825; font-weight: bold">&gt;</span>
    <span style="color: #6ab825; font-weight: bold">&lt;/iframe&gt;</span>
  <span style="color: #6ab825; font-weight: bold">&lt;/div&gt;</span>
  </pre></div>
  <!-- End HTML generated using hilite.me -->
  #+end_html

  #+begin_html
  <div style="width:300px; display:inline-block; float:right;
              border:1px solid #aaa; padding:0px; margin-left:10px;">
    <iframe src="http://v.btranslator.org?lng=sq&proj=ICT_sq"
	    width="100%" height="395px"
	    seamless="seamless" frameborder="0">
    </iframe>
  </div>
  #+end_html

  #+begin_html
  <div style="width:300px; display:inline-block;
	      float:right; border:1px solid #aaa; padding:5px;">
    <h3 style="margin-top:0px; color:#2a2;">Vocabulary: ICT_sq</h3>

    <iframe src="https://btranslator.org/vocabulary/ICT_sq?display=iframe"
	    width="100%" height="350px"
	    seamless="seamless" frameborder="0">
    </iframe>
  </div>
  #+end_html

  #+begin_html
  <p style="clear:both"> </p>
  #+end_html


* Connecting to social networks.

** Disqus

   Create a discussion forum at https://disqus.com/admin/create/ and
   put its name on ~config.js~.


** Twitter

   Try something like this on terminal:
   #+begin_example
   curl https://btranslator.org/tweet/sq/vocabulary/ICT_sq?url=http://v.btranslator.org
   #+end_example
   Or open it it browser:
   https://btranslator.org/tweet/sq/vocabulary/ICT_sq?url=http://v.btranslator.org

   Each time it will return a random term from the vocabulary, in a
   format suitable for twitter. To make the process automatic, you can
   use a script like [[https://github.com/B-Translator/btr_client/blob/master/utils/twitter.sh][twitter.sh]]:
   #+begin_example
   #!/bin/bash
   ### Send tweets from command line.

   t='/usr/local/bin/t'
   tweet=$(curl https://btranslator.org/tweet/sq/vocabulary/ICT_sq?url=http://v.btranslator.org)
   mention=$($t followings | sort -R | tail -1)
   $t update "$tweet @$mention"
   #+end_example

   In Linux, calling this script can be automated with a cron job. For
   example you can create the file ~/etc/cron.d/twitter~ with a
   content like this:
   #+begin_example
   ### first create a user with `adduser twitter`
   20 */12 * * *  twitter  /home/twitter/twitter.sh > /dev/null 2>&1

   ### uncomment this line only for debugging
   #*/5 * * * *  twitter  /home/twitter/twitter.sh
   #+end_example

   For instructions on how to install the *t* twitter client, see:
   http://xmodulo.com/2013/12/access-twitter-command-line-linux.html


** RSS

   Try something like this on terminal:
   #+begin_example
   curl https://btranslator.org/rss-feed/sq/vocabulary/ICT_sq?url=http://v.btranslator.org
   #+end_example
   Or open it it browser:
   https://btranslator.org/rss-feed/sq/vocabulary/ICT_sq?url=http://v.btranslator.org

   It return a RSS feed of the latest translations. Latest means
   yesterday. Results are cached, so last minute translations may not
   appear on the list.

   There services like https://dlvr.it/ which can connect to rss feeds
   and share the latest items to social networks (Facebook, LinkedIn,
   etc.) See this article for some other tools:
   http://www.twelveskip.com/guide/blogging/1189/best-auto-sharing-tools-social-media


* Creating vocabularies on the server

  *Note:* If you want to use https://btranslator.org as a server,
  contact me and I can create a new vocabulary for you.

  + Make sure that the language of vocabulary is supported:

    - Go to B-Translator server:
      #+begin_example
      docker-enter btr
      cd /var/www/btr/profiles/btr_server/
      #+end_example

    - Make sure that there is an entry for this language at the list
      of languages =admin/languages=.

    - Run the configuration script ~install/config/languages.sh~:
      #+begin_example
      ==> # install/config/languages.sh

      ===> Languages supported by B-Translator Server

      Do not remove 'fr', because sometimes French translations
      are used instead of template files (when they are missing).

      Enter language codes [fr]: fr de it es sq bg fi tr mk

      You are about to execute 'vset btr_languages fr de it es sq bg fi tr mk' non-interactively (--yes forced) on all of the following targets:
	@local_btr.btr
	@local_btr.btr_dev
      Continue?  (y/n): y
      local_btr.btr_dev >> btr_languages was set to "fr de it es sq bg fi tr mk".              [success]
      local_btr.btr     >> btr_languages was set to "fr de it es sq bg fi tr mk".              [success]
      You are about to execute 'php-eval module_load_include('inc', 'btrCore', 'btrCore.admin'); btrCore_config_set_languages();' non-interactively (--yes forced) on all of the following targets:
	@local_btr.btr
	@local_btr.btr_dev
      Continue?  (y/n): y
      You are about to execute 'language-add fr' non-interactively (--yes forced) on all of the following targets:
	@local_btr.btr
	@local_btr.btr_dev
      Continue?  (y/n): y
      local_btr.btr_dev >> The language with code fr already exists.                           [warning]
      local_btr.btr     >> The language with code fr already exists.                           [warning]

      [ . . . . . . . . . . . . . . . . . . . . . ]
      #+end_example

  + Create a vocabulary:
    #+begin_example
    drush @btr btrv-add ICT sq $(pwd)/ICT_sq.po
    #+end_example

    The name of the vocabulary is *ICT_sq* (having the language code
    as an appendix). The PO file that is used to initialize the
    vocabulary must have the same name as the vocabulary. Each entry
    in the PO file must have the name of the vocabulary as a context,
    like this:
    #+begin_example
    msgctxt "ICT_sq"
    #+end_example

    However the PO file is optional and it can be omitted in order to
    create an empty vocabulary (terms can be added from the
    application).

    You can also get a list of vocabularies and delete a vocabulary:
    #+begin_example
    drush @btr btrv-ls
    drush @btr btrv-del ICT sq
    #+end_example
